server {
  listen 3000; # Change this from 80 to 3000
  server_name localhost;

  location / {
    root /usr/share/nginx/html/home-automation-ui;
    index index.html;
    try_files $uri $uri/ /index.html;
  }
}